### ISSUE TITLE
Game crashing when i try to use Dyenamicsandfriends in my modpack

### ISSUE THREAD

**Issue by Patronelli** [JDKDigital/dyenamicsandfriends#1]
Version 1.19.2 - Forge 43.2.0
Minecraft crash report: https://pastebin.com/VHt09DjC

**Comment by JaisDK** [comment]
You need to add Dyenamics as well. It's a required dependency now that it has finally been updated

https://www.curseforge.com/minecraft/mc-mods/dyenamics/files/4366787

**Comment by JaisDK** [comment]
Dyenamics messed up their version tagging when uploading, download the mod again now that they've fixed it.
