### ISSUE TITLE
Dyenamics and Friends has failed to load correctly.

### ISSUE THREAD

**Issue by KodYazanDruid** [JDKDigital/dyenamicsandfriends#10]
There is already issue for https://github.com/JDKDigital/dyenamicsandfriends/issues/9 but i am using latest (dyenamicsandfriends-1.18.2-0.1.5.2.jar) avaliable and still getting the crash.

Crash log:
[crash-2023-06-14_12.45.21-fml.txt](https://github.com/JDKDigital/dyenamicsandfriends/files/11744293/crash-2023-06-14_12.45.21-fml.txt)

**Comment by KodYazanDruid** [comment]
Seems like  you fixed for 1.19.2 bur forgot the 1.18.2 lol.

**Comment by JaisDK** [comment]
yup

Didn't forget, it was just only reported for 1.19

**Comment by JaisDK** [comment]
I put up a new version, give it 10 minutes to be approved.

**Comment by KodYazanDruid** [comment]
Thanks for being fast.
