### ISSUE TITLE
Game Crashes Upon Using Dyenamics and Friends

### ISSUE THREAD

**Issue by PhweeDev** [JDKDigital/dyenamicsandfriends#2]
It says I'm missing the mod.. yet I literally have it. 

https://paste.gg/p/anonymous/91ef6e11a3ed4829a6a450c313c8bb35

**Comment by JaisDK** [comment]
Did you add Dyenamics as well? It's a required dependency now that it has finally been updated

https://www.curseforge.com/minecraft/mc-mods/dyenamics/files/4366787

**Comment by JaisDK** [comment]
Dyenamics messed up their version tagging when uploading, can you try downloading Dyenamics again now that they've fixed it? Delete the one you already have.

**Comment by PhweeDev** [comment]
It works. thanks :)
