### ISSUE TITLE
FurnishCompat issue with the new Furnish release

### ISSUE THREAD

**Issue by Wouink** [JDKDigital/dyenamicsandfriends#3]
Hi, I'm Wouink, the dev of Furnish.

I just learned you were adding compatibility with Furnish in your mod and I feel very honored!

I released a new version of Furnish which changes a few things in the code base, which creates a crash when using Dyenamics and Friends alongside -- see [this issue](https://github.com/Wouink/furnish/issues/27).

The fix should be easy, replace every occurence of `FurnishItems.Furnish_ItemGroup` with `Furnish.CREATIVE_TAB` in `cy.jdkdigital.dyenamicsandfriends.compat.FurnishCompat`. I think that's all that needs to be changed.

Best Regards,
Wouink

**Comment by JaisDK** [comment]
Thanks for letting me know! Is the change for both 1.18.2 and 1.19.2?

**Comment by JaisDK** [comment]
https://www.curseforge.com/minecraft/mc-mods/dyenamicsandfriends/files/4449907
