### ISSUE TITLE
Crash when placing a sleeping bag Forge 1.18.2

### ISSUE THREAD

**Issue by Bitslayn** [JDKDigital/dyenamicsandfriends#6]
Game crashes whenever I try to place a sleeping bag

Log (No crash report generated)
https://mclo.gs/VYAposK

**Comment by Bitslayn** [comment]
There was only a crash log generated when I had the Better Third Person mod enabled. It might still be relevant https://bytebin.lucko.me/Za5JD7H7R0

**Comment by Bitslayn** [comment]
Seems to be crashing when I place any block in this mod 🤔

**Comment by JaisDK** [comment]
Looks like botania is doing something that initializes the blocks in a non-compatible way. I'll look into it.

**Comment by Bitslayn** [comment]
I removed the Botania mod so it's not urgent

**Comment by JaisDK** [comment]
The mod is crashing with Botania, of course it's urgent :D
