### ISSUE TITLE
Crash w/ newest Create

### ISSUE THREAD

**Issue by WenXin20** [JDKDigital/dyenamicsandfriends#7]
```
Minecraft v1.19.2
Forge v43.2.7
Create v0.5.1a
Dyenamics & Friends v0.1.5.1
```

After updating create, Dyenamics & Friends crashes on launch.
[Crash Report](https://gist.github.com/WenXin20/be6e58657c345191db678d2d283003ad)

**Comment by JaisDK** [comment]
fixed
