### ISSUE TITLE
Quark shard recipe discrepancy

### ISSUE THREAD

**Issue by knighthawkUnlimited** [JDKDigital/dyenamicsandfriends#8]
Nothing game breaking, but when I try to craft a glass block out of 4 of it's shards I get a dirty glass block.

1.19.2

**Comment by JaisDK** [comment]
install https://www.curseforge.com/minecraft/mc-mods/polymorph until I find out how I can get it to load my recipes before the dirty glass one.

**Comment by JaisDK** [comment]
fixed in new version
